server:
  port: 9702

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      
      - id: user-microservice
        uri: lb://user-microservice
        predicates:
        - Path=/user/**
        filters:
        - name: CircuitBreaker
          args:
            name: user-microservice
            fallbackuri: forward:/userservicefallback
            
      - id: contact-microservice
        uri: lb://contact-microservice
        predicates:
        - Path=/contact/**
        filters:
        - name: CircuitBreaker
          args:
            name: contact-microservice
            fallbackuri: forward:/contactservicefallback
            
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream